language: go

env:
  global:
  - GO111MODULE=on
#  - GOPROXY=https://proxy.golang.org

go:
 - "1.13"

before_script:
 - go get golang.org/x/lint/golint

script:
 - diff -u <(echo -n) <(gofmt -d -s .)
 - golint -set_exit_status $(go list ./...)
 - go vet .
 - go test -v ./...

cache:
  directories:
   - $HOME/gopath/pkg/mod
